#--------------------#
#                    #
#  ╦ ╦╦═╗  ╔═╗╔═╗╦   #
#  ║║║╠╦╝  ╠═╣╠═╝║   #
#  ╚╩╝╩╚═  ╩ ╩╩  ╩   #
#                    #
#--------------------#

main: WorldRegion
version: 1.5
api-version: 1.13
name: WorldRegion
author: PablockDA
#commands:
#  worldregion:
#    aliases: [worldregion]
#    description: WorldRegion main command*/